import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
let client;globalThis.passwordTestClient=()=>client;
const source=readFileSync(new URL('../app/auth/password/route.ts',import.meta.url),'utf8').replace(/import .*mentoringClient.*\n/,'const mentoringClient=async()=>globalThis.passwordTestClient();\n').replace(/import .*useSupabase.*\n/,'const useSupabase=()=>true;\n');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {POST}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function request(body,origin='https://portal.test'){return new Request('https://portal.test/auth/password',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});}
function setup(){const calls=[];client={auth:{signInWithPassword:async()=>({error:null}),signOut:async()=>{calls.push('signout');return {};},signUp:async()=>({error:null}),resetPasswordForEmail:async()=>({error:null}),getUser:async()=>({data:{user:null},error:null}),updateUser:async()=>{calls.push('update');return {error:null};}},rpc:async()=>({data:'mentor',error:null})};return calls;}
test('password login rejects cross-origin requests before authentication',async()=>{setup();assert.equal((await POST(request({mode:'signin'},'https://other.test'))).status,403);});
test('password login checks database access and signs out unapproved users',async()=>{const calls=setup();let r=await POST(request({mode:'signin',email:'mentor@example.com',password:'correct'}));assert.equal((await r.json()).redirect,'/');client.rpc=async()=>({data:null,error:null});r=await POST(request({mode:'signin',email:'mentor@example.com',password:'correct'}));assert.equal(r.status,403);assert.deepEqual(calls,['signout']);});
test('login failures never reveal provider messages or account existence',async()=>{setup();client.auth.signInWithPassword=async()=>({error:{message:'private provider detail'}});const r=await POST(request({mode:'signin',email:'mentor@example.com',password:'wrong'}));assert.equal(r.status,401);assert.ok(!(await r.text()).includes('private provider detail'));});
test('account creation requires a strong length and retains verification messaging',async()=>{setup();assert.equal((await POST(request({mode:'signup',email:'mentor@example.com',password:'short'}))).status,400);const r=await POST(request({mode:'signup',email:'mentor@example.com',password:'long-enough-password'}));assert.equal(r.status,200);assert.match((await r.json()).message,/confirm/);});
test('password reset response is generic and password updates require a verified session',async()=>{const calls=setup();const r=await POST(request({mode:'reset',email:'mentor@example.com'}));assert.match((await r.json()).message,/If this email has an account/);assert.equal((await POST(request({mode:'update',password:'long-enough-password'}))).status,401);assert.deepEqual(calls,[]);client.auth.getUser=async()=>({data:{user:{id:'verified'}},error:null});assert.equal((await POST(request({mode:'update',password:'long-enough-password'}))).status,200);assert.deepEqual(calls,['update','signout']);});
