'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Attachment={name:string;path:string;url?:string};
export default function ProfileFiles({boyId}:{boyId:string}){
 const [files,setFiles]=useState<Attachment[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [page,setPage]=useState(0);const [more,setMore]=useState(false);const [revision,setRevision]=useState(0);
 const endpoint='/api/files?boyId='+encodeURIComponent(boyId);
 useEffect(()=>{let active=true;setError('');fetch(endpoint+'&offset='+page*100).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json();}).then(r=>{if(active){setFiles(r.files);setMore(r.hasMore);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[endpoint,page,revision]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setError('');try{const response=await fetch(endpoint,{method:'POST',body:new FormData(form)});if(!response.ok)throw new Error(await response.text());form.reset();setRevision(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}
 async function remove(file:Attachment){if(!window.confirm('Delete '+file.name+'?'))return;setBusy(true);try{const r=await fetch(endpoint,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:file.path})});if(!r.ok)throw new Error(await r.text());setRevision(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Delete failed');}finally{setBusy(false);}}
 return <section className="panel" style={{padding:20,marginTop:20}}><h3>Photos and files</h3><p>Private to approved portal users. JPG, PNG, WebP or PDF; up to 4 MB.</p>{error&&<p role="alert">{error}</p>}<form onSubmit={upload}><input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/><button disabled={busy}>{busy?'Saving...':'Upload'}</button></form><ul>{files.map(file=><li key={file.path}><a href={file.url} target="_blank" rel="noreferrer">{file.name}</a> <button disabled={busy} onClick={()=>void remove(file)}>Delete</button></li>)}</ul><button onClick={()=>setRevision(x=>x+1)}>Refresh file links</button> <button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button> <button disabled={!more} onClick={()=>setPage(p=>p+1)}>Next</button></section>;
}
