'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Field={key:string;label:string;type?:string;options?:string[];required?:boolean};
const sections:Record<string,{title:string;fields:Field[]}>= {
 calendarEvents:{title:'Calendar',fields:[{key:'title',label:'Event / activity',required:true},{key:'startDate',label:'Start date',type:'date',required:true},{key:'endDate',label:'End date',type:'date'},{key:'type',label:'Type'},{key:'availability',label:'Availability'},{key:'semester',label:'Semester'},{key:'scope',label:'Institution / scope'},{key:'note',label:'Planning note'},{key:'source',label:'Source'}]},
 websiteSettings:{title:'Website Settings',fields:[{key:'value',label:'Value'}]},
 mentors:{title:'Mentors',fields:[{key:'name',label:'Mentor name',required:true},{key:'email',label:'Email',type:'email'},{key:'tone',label:'Colour',options:['saffron','green','blue','plum','gold']}]},
 programTypes:{title:'Program Types',fields:[{key:'name',label:'Program name',required:true}]},
 access:{title:'Portal Access',fields:[{key:'name',label:'Name',required:true},{key:'role',label:'Role',options:['mentor','admin']},{key:'active',label:'Active',options:['true','false']}]},
};
type Row=Record<string,unknown>&{id:string};
function SettingHelp({row}:{row:Row}){const source=row.sourceRow as Record<string,unknown>|undefined;return source?<aside className="panel" style={{padding:16,marginTop:16}}><strong>{String(source.Control||row.id)}</strong><p>{String(source['What It Changes']||'')}</p><p>Allowed values: {String(source['Allowed Values']||'Text')}</p></aside>:null;}
export default function Manager(){
 const [section,setSection]=useState('calendarEvents');const [rows,setRows]=useState<Row[]>([]);const [editing,setEditing]=useState<Row|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('section');if(requested&&sections[requested])setSection(requested);},[]);
 useEffect(()=>{let active=true;setLoading(true);setError('');setEditing(null);fetch('/api/manage?kind='+section).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json();}).then(data=>{if(active)setRows(data.records);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[section]);
 async function write(body:object){setBusy(true);setError('');try{const response=await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,requestId:crypto.randomUUID()})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save');const r=await fetch('/api/manage?kind='+section);if(!r.ok)throw new Error('Saved, but the updated list could not be loaded. Reload this page.');setRows((await r.json()).records);setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setBusy(false);}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const id=String(values.id);delete values.id;await write({action:'manage_record',kind:section,id,values});}
 return <main className="page-shell" style={{padding:'32px 20px'}}><a href="/">Back to dashboard</a><h1>Manage mentoring</h1><p>Changes are saved directly to the mentoring database.</p><nav className="nav-tabs">{Object.entries(sections).map(([key,s])=><button key={key} disabled={busy} onClick={()=>setSection(key)} className={section===key?'active':''}>{s.title}</button>)}</nav>
 <p><a className="primary-button" href="/manage/data">Import, export and backups</a></p>
 {error&&<p role="alert" className="error-banner">{error}</p>}
 <h2>{sections[section].title}</h2><button className="primary-button" disabled={busy||loading} onClick={()=>setEditing({id:section==='access'||section==='websiteSettings'?'':crypto.randomUUID()})}>Add record</button>
 {section==='websiteSettings'&&editing&&<SettingHelp row={editing}/>}
 {loading?<p role="status">Loading...</p>:<div className="table-wrap"><table><thead><tr><th>Record</th><th>Details</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{String(row.name||row.title||row.id)}</td><td>{String(row.value??row.startDate??row.role??'')}</td><td><button disabled={busy} onClick={()=>setEditing(row)}>Edit</button> <button disabled={busy} onClick={()=>{if(window.confirm('Delete this record? Linked mentors and program types cannot be deleted while in use.'))void write({action:'delete_managed_record',kind:section,id:row.id});}}>Delete</button></td></tr>)}</tbody></table></div>}
 {editing&&<form className="panel record-form" key={section+editing.id} onSubmit={save} style={{marginTop:20,padding:24}}><h3 className="full">Edit {sections[section].title}</h3><label className="full"><span>{section==='access'?'Account email':section==='websiteSettings'?'Setting name':'Record ID'}</span><input name="id" defaultValue={editing.id} required readOnly={rows.some(r=>r.id===editing.id)||(section!=='access'&&section!=='websiteSettings')} type={section==='access'?'email':'text'}/></label>{sections[section].fields.map(field=><label key={field.key}><span>{field.label}</span>{field.options?<select name={field.key} defaultValue={String(editing[field.key]??field.options[0])}>{field.options.map(v=><option key={v}>{v}</option>)}</select>:<input name={field.key} type={field.type||'text'} defaultValue={String(editing[field.key]??'')} required={field.required}/>}</label>)}<div className="full"><button className="primary-button" disabled={busy}>{busy?'Saving...':'Save'}</button> <button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 </main>;
}
