begin;
create schema if not exists mentoring_private;
revoke all on schema mentoring_private from public, anon, authenticated;
create table public.mentoring_access (
 email text primary key check(email=lower(trim(email))), name text not null default '',
 role text not null check(role in ('admin','mentor')), active boolean not null default false,
 source jsonb not null default '{}'::jsonb
);
-- JSONB preserves the existing application's fields and any source metadata.
-- Collection keys, relationship indexes, policies and transactional RPCs enforce integrity.
create table public.mentoring_records (
 kind text not null check(kind in ('mentors','programTypes','boys','programs','attendance','invitations','calendarEvents','websiteContent','websiteSettings')),
 id text not null check(length(trim(id))>0), data jsonb not null check(jsonb_typeof(data)='object'),
 position bigint generated by default as identity, primary key(kind,id)
);
create index mentoring_boys_mentor on public.mentoring_records ((data->>'mentorId')) where kind='boys';
create index mentoring_programs_type on public.mentoring_records ((data->>'programTypeId')) where kind='programs';
create index mentoring_history_boy on public.mentoring_records (kind,(data->>'boyId')) where kind in ('attendance','invitations');
create unique index mentoring_session_boy on public.mentoring_records (kind,(data->>'programId'),(data->>'boyId')) where kind in ('attendance','invitations');
create table mentoring_private.requests (
 user_id uuid not null, request_id uuid not null, payload jsonb not null, result jsonb not null,
 created_at timestamptz not null default now(), primary key(user_id,request_id)
);
create table mentoring_private.source_snapshots (
 id uuid primary key default gen_random_uuid(), imported_at timestamptz not null default now(),
 source_id text not null, payload jsonb not null
);

create function public.mentoring_role() returns text language sql stable security definer set search_path='' as $$
 select a.role from public.mentoring_access a join auth.users u on lower(u.email)=a.email
 where u.id=auth.uid() and u.email_confirmed_at is not null and a.active;
$$;
revoke all on function public.mentoring_role() from public,anon;
grant execute on function public.mentoring_role() to authenticated;
alter table public.mentoring_access enable row level security;
alter table public.mentoring_records enable row level security;
create policy mentoring_access_read on public.mentoring_access for select to authenticated
 using (public.mentoring_role()='admin');
create policy mentoring_records_read on public.mentoring_records for select to authenticated
 using (public.mentoring_role() is not null);
revoke all on public.mentoring_records,public.mentoring_access from anon,authenticated;
grant select on public.mentoring_records,public.mentoring_access to authenticated;
grant all on public.mentoring_records,public.mentoring_access to service_role;
grant usage,select on all sequences in schema public to service_role;

create function public.mentoring_state() returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb='{}'; k text; v jsonb; viewer jsonb;
begin
 if public.mentoring_role() is null then raise exception 'Access denied' using errcode='42501'; end if;
 foreach k in array array['mentors','programTypes','boys','programs','attendance','invitations','calendarEvents'] loop
  select coalesce(jsonb_agg(data order by position,id),'[]') into v from public.mentoring_records where kind=k;
  result=result||jsonb_build_object(k,v);
 end loop;
 foreach k in array array['websiteContent','websiteSettings'] loop
  select coalesce(jsonb_object_agg(id,data->'value'),'{}') into v from public.mentoring_records where kind=k;
  result=result||jsonb_build_object(k,v);
 end loop;
 select jsonb_build_object('email',a.email,'name',a.name,'role',a.role) into viewer
 from public.mentoring_access a join auth.users u on lower(u.email)=a.email where u.id=auth.uid();
 return result||jsonb_build_object('viewer',viewer,'backend','supabase','refreshedAt',now());
end; $$;
revoke all on function public.mentoring_state() from public,anon;
grant execute on function public.mentoring_state() to authenticated;

create function mentoring_private.required(v text,label text) returns text language plpgsql immutable as $$
begin if coalesce(trim(v),'')='' then raise exception '% is required',label; end if; return trim(v); end; $$;
create function mentoring_private.clean(v text,n integer) returns text language sql immutable as $$ select left(coalesce(trim(v),''),n); $$;
create function mentoring_private.parent(k text,i text) returns jsonb language plpgsql stable set search_path='' as $$
declare v jsonb; begin select data into v from public.mentoring_records where kind=k and id=i;
 if v is null then raise exception '% record was not found',k; end if; return v; end; $$;
create function mentoring_private.valid_date(v text) returns text language plpgsql immutable as $$
begin if coalesce(v,'') !~ '^\d{4}-\d{2}-\d{2}$' or to_char(v::date,'YYYY-MM-DD')<>v then raise exception 'Select a valid date'; end if; return v; end; $$;

create function public.mentoring_mutate(p_body jsonb,p_request_id uuid) returns jsonb
language plpgsql security definer set search_path='' as $$
declare
 a text=p_body->>'action'; k text; i text; old jsonb; v jsonb; parent jsonb; item record;
 changes jsonb='[]'; removed jsonb='[]'; result jsonb; prior mentoring_private.requests%rowtype;
 actor_email text; role_name text; status_value text; floor_value text; room_value text; type_id text;
begin
 role_name=public.mentoring_role();
 if role_name is null then raise exception 'Access denied' using errcode='42501'; end if;
 if p_request_id is null then raise exception 'Request ID required'; end if;
 -- A short database transaction serializes conflicting attendance/type changes.
 perform pg_advisory_xact_lock(27092026);
 select * into prior from mentoring_private.requests where user_id=auth.uid() and request_id=p_request_id;
 if found then
  if prior.payload<>p_body then raise exception 'Request ID already used'; end if;
  return prior.result;
 end if;
 select lower(u.email) into actor_email from auth.users u where u.id=auth.uid();
 if a in ('add_boy','update_boy') then
  k='boys'; i=case when a='add_boy' then gen_random_uuid()::text else p_body->>'boyId' end;
  old=case when a='add_boy' then '{}'::jsonb else mentoring_private.parent(k,i) end;
  perform mentoring_private.parent('mentors',p_body->>'mentorId');
  status_value=coalesce(p_body->>'status','Active');
  if status_value not in ('Active','Passive','Dropped') then raise exception 'Invalid boy status'; end if;
  room_value=mentoring_private.clean(p_body->>'hostel',150);
  floor_value=case when p_body ? 'floor' then upper(trim(p_body->>'floor')) else coalesce(old->>'floor','') end;
  if (floor_value<>coalesce(old->>'floor','') or room_value<>coalesce(old->>'hostel','')) and floor_value<>'' then
   if floor_value !~ '^B[0-9]$' then raise exception 'Select a floor from B0 to B9'; end if;
   if room_value !~ '^\d+$' then raise exception 'Select a room from 1 to 61'; end if;
   if room_value::numeric not between 1 and 61 then raise exception 'Select a room from 1 to 61'; end if;
  end if;
  v=old||jsonb_build_object('id',i,'name',mentoring_private.required(coalesce(p_body->>'name',old->>'name'),'Boy name'),
   'mentorId',p_body->>'mentorId','status',status_value,'hostel',room_value,'floor',floor_value,
   'contact',mentoring_private.clean(p_body->>'contact',24),'college',mentoring_private.clean(p_body->>'college',150),
   'branch',mentoring_private.clean(p_body->>'branch',100),'section',mentoring_private.clean(p_body->>'section',100),
   'comment',mentoring_private.clean(p_body->>'comment',1500));
  if a='add_boy' then v=v||jsonb_build_object('createdAt',now(),'createdBy',actor_email); end if;
 elsif a in ('add_program','update_program') then
  k='programs'; i=case when a='add_program' then gen_random_uuid()::text else p_body->>'programId' end;
  old=case when a='add_program' then '{}'::jsonb else mentoring_private.parent(k,i) end;
  type_id=p_body->>'programTypeId'; parent=mentoring_private.parent('programTypes',type_id);
  if exists(select 1 from public.mentoring_records x join public.mentoring_records y on y.kind='attendance' and y.data->>'boyId'=x.data->>'boyId'
   join public.mentoring_records p on p.kind='programs' and p.id=y.data->>'programId'
   where x.kind='attendance' and x.data->>'programId'=i and x.data->>'status'='Present' and y.data->>'status'='Present' and p.id<>i and p.data->>'programTypeId'=type_id)
  then raise exception 'Changing this Program Type would create duplicate Present credit'; end if;
  v=old||jsonb_build_object('id',i,'name',coalesce(nullif(mentoring_private.clean(p_body->>'name',180),''),parent->>'name'),
   'programTypeId',type_id,'programType',parent->>'name','date',mentoring_private.valid_date(p_body->>'date'),
   'venue',mentoring_private.clean(p_body->>'venue',200),'speaker',mentoring_private.clean(p_body->>'speaker',180),
   'createdAt',coalesce(old->>'createdAt',now()::text));
 elsif a in ('set_attendance','set_invitation') and not (a='set_invitation' and coalesce(p_body->>'invited','true')='false') then
  k=case when a='set_attendance' then 'attendance' else 'invitations' end;
  parent=mentoring_private.parent('programs',p_body->>'programId'); type_id=parent->>'programTypeId';
  parent=mentoring_private.parent('boys',p_body->>'boyId');
  select id,data into i,old from public.mentoring_records where kind=k and data->>'programId'=p_body->>'programId' and data->>'boyId'=p_body->>'boyId';
  i=coalesce(i,gen_random_uuid()::text); old=coalesce(old,'{}');
  v=old||jsonb_build_object('id',i,'programId',p_body->>'programId','boyId',p_body->>'boyId','mentorId',parent->>'mentorId','updatedAt',now(),'updatedBy',actor_email);
  if a='set_attendance' then
   status_value=p_body->>'status';
   if status_value is null or status_value not in ('Present','Absent','Late') then raise exception 'Select a valid attendance status'; end if;
   if status_value='Absent' then perform mentoring_private.required(p_body->>'reason','Absence reason'); end if;
   if status_value='Present' and exists(select 1 from public.mentoring_records t join public.mentoring_records p on p.kind='programs' and p.id=t.data->>'programId'
    where t.kind='attendance' and t.id<>i and t.data->>'boyId'=p_body->>'boyId' and t.data->>'status'='Present' and p.data->>'programTypeId'=type_id)
   then raise exception 'This boy is already Present for this Program Type'; end if;
   v=v||jsonb_build_object('status',status_value,'reason',mentoring_private.clean(p_body->>'reason',300));
  else v=v||jsonb_build_object('response',left(mentoring_private.required(p_body->>'response','Invitation response'),300)); end if;
 elsif a in ('delete_boy','delete_program','delete_attendance','delete_invitation') or (a='set_invitation' and coalesce(p_body->>'invited','true')='false') then
  if a in ('delete_boy','delete_program') then
   k=case when a='delete_boy' then 'boys' else 'programs' end; i=case when a='delete_boy' then p_body->>'boyId' else p_body->>'programId' end;
   perform mentoring_private.parent(k,i);
   for item in delete from public.mentoring_records where (kind=k and id=i) or
    (kind in ('attendance','invitations') and data->>(case when a='delete_boy' then 'boyId' else 'programId' end)=i) returning kind,id loop
    removed=removed||jsonb_build_array(jsonb_build_object('kind',item.kind,'id',item.id));
   end loop;
  else
   k=case when a='delete_attendance' then 'attendance' else 'invitations' end;
   perform mentoring_private.required(p_body->>'programId','Program'); perform mentoring_private.required(p_body->>'boyId','Boy');
   for item in delete from public.mentoring_records where kind=k and data->>'programId'=p_body->>'programId' and data->>'boyId'=p_body->>'boyId' returning id loop
    removed=removed||jsonb_build_array(jsonb_build_object('kind',k,'id',item.id));
   end loop;
  end if;
 elsif a='update_website_content' then
  if role_name<>'admin' then raise exception 'Only an Admin can update website wording' using errcode='42501'; end if;
  if jsonb_typeof(p_body->'values') is distinct from 'object' then raise exception 'Content values required'; end if;
  for item in select * from jsonb_each_text(p_body->'values') loop
   old=mentoring_private.parent('websiteContent',item.key);
   v=old||jsonb_build_object('id',item.key,'value',left(item.value,3000),'updatedAt',now(),'updatedBy',actor_email);
   update public.mentoring_records set data=v where kind='websiteContent' and id=item.key;
   changes=changes||jsonb_build_array(jsonb_build_object('kind','websiteContent','record',v));
  end loop; v=null;
 elsif a in ('manage_record','delete_managed_record') then
  if role_name<>'admin' then raise exception 'Admin access required' using errcode='42501'; end if;
  k=p_body->>'kind'; i=mentoring_private.required(p_body->>'id','Record ID');
  if k not in ('mentors','programTypes','calendarEvents','websiteSettings','access') then raise exception 'Unsupported management section'; end if;
  if k='access' then
   i=lower(i); v=p_body->'values';
   if i !~ '^[^ @]+@[^ @]+\.[^ @]+$' then raise exception 'Valid email required'; end if;
   if a='delete_managed_record' or not coalesce((v->>'active')::boolean,false) or coalesce(v->>'role','')<>'admin' then
    if exists(select 1 from public.mentoring_access where email=i and active and role='admin') and (select count(*) from public.mentoring_access where active and role='admin')<=1 then raise exception 'Keep at least one active administrator'; end if;
   end if;
   if a='delete_managed_record' then delete from public.mentoring_access where email=i;
   else
    if coalesce(v->>'role','') not in ('admin','mentor') then raise exception 'Invalid access role'; end if;
    insert into public.mentoring_access(email,name,role,active) values(i,coalesce(v->>'name',''),v->>'role',coalesce((v->>'active')::boolean,false))
    on conflict(email) do update set name=excluded.name,role=excluded.role,active=excluded.active;
   end if; v=null;
  elsif a='delete_managed_record' then
   if k='mentors' and exists(select 1 from public.mentoring_records where kind='boys' and data->>'mentorId'=i) then raise exception 'Reassign this mentor''s boys first'; end if;
   if k='programTypes' and exists(select 1 from public.mentoring_records where kind='programs' and data->>'programTypeId'=i) then raise exception 'This type is used by programs'; end if;
   delete from public.mentoring_records where kind=k and id=i;
   removed=removed||jsonb_build_array(jsonb_build_object('kind',k,'id',i)); v=null;
  else
   select data into old from public.mentoring_records where kind=k and id=i;
   v=coalesce(old,'{}')||coalesce(p_body->'values','{}')||jsonb_build_object('id',i);
   if k in ('mentors','programTypes') then perform mentoring_private.required(v->>'name','Name'); end if;
   if k='mentors' then v=v||jsonb_build_object('initials',left(v->>'name',2),'tone',coalesce(v->>'tone','green')); end if;
   if k='calendarEvents' then
    perform mentoring_private.required(v->>'title','Title'); perform mentoring_private.valid_date(v->>'startDate');
    if coalesce(v->>'endDate','')<>'' then perform mentoring_private.valid_date(v->>'endDate'); if v->>'endDate'<v->>'startDate' then raise exception 'End date precedes start date'; end if; end if;
   end if;
   if k='websiteSettings' then v=v||jsonb_build_object('value',coalesce(v->>'value','')); end if;
   if k='programTypes' then
    for item in update public.mentoring_records set data=data||jsonb_build_object('programType',v->>'name') where kind='programs' and data->>'programTypeId'=i returning data loop
     changes=changes||jsonb_build_array(jsonb_build_object('kind','programs','record',item.data));
    end loop;
   end if;
  end if;
 else raise exception 'Unsupported action'; end if;
 if v is not null then
  insert into public.mentoring_records(kind,id,data) values(k,i,v) on conflict(kind,id) do update set data=excluded.data;
  changes=changes||jsonb_build_array(jsonb_build_object('kind',k,'record',v));
 end if;
 result=jsonb_build_object('upserts',changes,'deletes',removed,'refreshedAt',now());
 insert into mentoring_private.requests(user_id,request_id,payload,result) values(auth.uid(),p_request_id,p_body,result);
 return result;
end; $$;
revoke all on function public.mentoring_mutate(jsonb,uuid) from public,anon;
grant execute on function public.mentoring_mutate(jsonb,uuid) to authenticated;
revoke all on all functions in schema mentoring_private from public,anon,authenticated;
commit;
